### ISSUE TITLE
Can I use it on MacOS ？

### ISSUE THREAD

**Issue by GnaixEuy** [wakatime/office-wakatime#9] opened 2021-09-09 02:18 UTC
How do I use plug-ins in office on MacOS system? Will they be supported in the future?

**Comment by rjdbcm** [comment] 2021-10-16 03:18
I have yet to find a way to get it to install on MacOS. Would be nice.

**Comment by DiegoCao** [comment] 2021-10-29 22:55
> I have yet to find a way to get it to install on MacOS. Would be nice.0

May I ask how can it be installed in MacOS?

**Comment by gandarez** [comment] 2021-11-05 20:47
Not yet but we plan to support it.

**Comment by gandarez** [comment] 2022-02-15 15:52
Duplicate of https://github.com/wakatime/office-wakatime/issues/2

**Closed as completed by gandarez** 2022-02-15 15:52 UTC
